
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SHOHIN_IMG_FILE]') AND type in (N'U'))
DROP TABLE [dbo].[SHOHIN_IMG_FILE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SHOHIN_IMG_FILE](
	[SIF_PIC_UNIT] [nvarchar](100) NOT NULL,
	[SIF_SCD] [bigint] NOT NULL,
	[SIF_SFILENAME] [varchar](30) NOT NULL,
	[SIF_IMG_TYPE] [nvarchar](20) NOT NULL,
	[SIF_IMG_PATH] [nvarchar](300) NOT NULL,
	[SIF_IMG_EXIST] [tinyint] NOT NULL,
	[SIF_FILE_CREATE] [datetime] NULL,
	[SIF_FILE_LASTWRITE] [datetime] NULL,
	[SIF_YMD] [datetime] NOT NULL,
	[SIF_COMPUTER] [nvarchar](100) NOT NULL,
	[SIF_USER] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_SHOHIN_IMG_FILE] PRIMARY KEY CLUSTERED 
(
	[SIF_PIC_UNIT] ASC,
	[SIF_SCD] ASC,
	[SIF_SFILENAME] ASC,
	[SIF_IMG_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
